/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as NouveauRouteImport } from './routes/nouveau'
import { Route as HistoriqueRouteImport } from './routes/historique'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DossierIdRouteImport } from './routes/dossier.$id'

const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const NouveauRoute = NouveauRouteImport.update({
  id: '/nouveau',
  path: '/nouveau',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriqueRoute = HistoriqueRouteImport.update({
  id: '/historique',
  path: '/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierIdRoute = DossierIdRouteImport.update({
  id: '/dossier/$id',
  path: '/dossier/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historique': typeof HistoriqueRoute
  '/nouveau': typeof NouveauRoute
  '/parametres': typeof ParametresRoute
  '/dossier/$id': typeof DossierIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historique': typeof HistoriqueRoute
  '/nouveau': typeof NouveauRoute
  '/parametres': typeof ParametresRoute
  '/dossier/$id': typeof DossierIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/historique': typeof HistoriqueRoute
  '/nouveau': typeof NouveauRoute
  '/parametres': typeof ParametresRoute
  '/dossier/$id': typeof DossierIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/historique' | '/nouveau' | '/parametres' | '/dossier/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/historique' | '/nouveau' | '/parametres' | '/dossier/$id'
  id:
    | '__root__'
    | '/'
    | '/historique'
    | '/nouveau'
    | '/parametres'
    | '/dossier/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoriqueRoute: typeof HistoriqueRoute
  NouveauRoute: typeof NouveauRoute
  ParametresRoute: typeof ParametresRoute
  DossierIdRoute: typeof DossierIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nouveau': {
      id: '/nouveau'
      path: '/nouveau'
      fullPath: '/nouveau'
      preLoaderRoute: typeof NouveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historique': {
      id: '/historique'
      path: '/historique'
      fullPath: '/historique'
      preLoaderRoute: typeof HistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier/$id': {
      id: '/dossier/$id'
      path: '/dossier/$id'
      fullPath: '/dossier/$id'
      preLoaderRoute: typeof DossierIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoriqueRoute: HistoriqueRoute,
  NouveauRoute: NouveauRoute,
  ParametresRoute: ParametresRoute,
  DossierIdRoute: DossierIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
